"""
Generate explicit hypergeometric parameters for ALL unexplored (s, p) pairs.
This is the FIRST deliverable any new formula paper needs.
The parameters are exact rational numbers from the descent formula.
Only A, B, z0, and C remain to be computed (requires SageMath).
"""
from fractions import Fraction
from collections import defaultdict

ATOMIC = {
    "s=1/2": {"a": [Fraction(1,2), Fraction(1,2)], "b": [Fraction(1,1)], "N": 2},
    "s=1/3": {"a": [Fraction(1,3), Fraction(2,3)], "b": [Fraction(1,1)], "N": 3},
    "s=1/4": {"a": [Fraction(1,4), Fraction(3,4)], "b": [Fraction(1,1)], "N": 4},
    "s=1/6": {"a": [Fraction(1,6), Fraction(5,6)], "b": [Fraction(1,1)], "N": 6},
}

KNOWN_TRIPLES = {
    ("s=1/2",2,1),("s=1/2",3,3),("s=1/2",5,4),("s=1/2",7,7),
    ("s=1/3",2,2),("s=1/3",3,3),("s=1/3",5,5),("s=1/3",7,1),
    ("s=1/4",2,1),("s=1/4",3,3),("s=1/4",5,2),("s=1/4",7,7),
    ("s=1/6",2,2),("s=1/6",3,1),("s=1/6",5,5),("s=1/6",7,3),
    ("s=1/6",11,11),
}

def translation_Sp(seed_a, seed_b, p):
    """Zudilin's exact descent on hypergeometric parameters."""
    def split_param(r):
        result = []
        for j in range(p):
            result.append(Fraction(r.numerator + j * r.denominator,
                                 p * r.denominator))
        return result

    def normalize(params):
        seen = set()
        result = []
        for r in params:
            red = Fraction(r.numerator % r.denominator, r.denominator)
            if red.numerator == 0 or red == Fraction(1,1):
                continue
            key = (red.numerator, red.denominator)
            if key not in seen:
                seen.add(key)
                result.append(red)
        return sorted(result, key=lambda x: (x.denominator, x.numerator))

    new_a = []
    for ai in seed_a:
        new_a.extend(split_param(ai))
    new_a = normalize(new_a)

    new_b = []
    for bj in seed_b:
        new_b.extend(split_param(bj))
    for j in range(1, p):
        new_b.append(Fraction(j, p))
    new_b = normalize(new_b)

    return new_a, new_b

def format_param(r):
    return f"{r.numerator}/{r.denominator}"

print("=" * 78)
print("NEW RAMANUJAN-TYPE FORMULA CANDIDATES — Hypergeometric Parameters")
print("  Generated by the three-layer framework: D o M_p o H")
print("=" * 78)

primes = [2,3,5,7,11,13,17,19,23,29,31]
discriminants = [1,2,3,7,11,19,43,67,163]

discoveries = []
for name, seed in ATOMIC.items():
    N0 = seed["N"]
    for p in primes:
        if p % N0 == 0:
            continue
        a_new, b_new = translation_Sp(seed["a"], seed["b"], p)
        for d in discriminants:
            triple = (name, p, d)
            if triple in KNOWN_TRIPLES:
                continue
            discoveries.append({
                "seed": name, "p": p, "d": d,
                "a": a_new, "b": b_new,
                "num_a": len(a_new), "num_b": len(b_new),
            })

print(f"\n  {len(discoveries)} unexplored (s,p,d) triples found.\n")

# Group by seed and p to show families
print("--- NEW PARAMETER FAMILIES (grouped by seed + prime) ---\n")
families = defaultdict(list)
for disc in discoveries:
    key = (disc["seed"], disc["p"])
    families[key].append(disc)

for (name, p), discs in sorted(families.items()):
    d_list = sorted([d["d"] for d in discs])
    # Get representative parameters
    rep = discs[0]
    a_str = ", ".join(format_param(r) for r in rep["a"])
    b_str = ", ".join(format_param(r) for r in rep["b"])

    print(f"[{name}, p={p}]  d in {d_list}")
    print(f"  a = [{a_str}]")
    print(f"  b = [{b_str}]")
    print(f"  Series form: sum (a_1)_n...(a_{rep['num_a']})_n / "
          f"((b_1)_n...(b_{rep['num_b']})_n * n!^{rep['num_a']-rep['num_b']}) "
          f"* (A + Bn) * z0^n = C/pi")
    print()

print("=" * 78)
print("NEXT STEP: Install SageMath (via conda) to:")
print("  1. Compute exact CM singular moduli z0 for each (d, p, N0)")
print("  2. Run Zeilberger's algorithm → find A, B")
print("  3. PSLQ integer relation → find exact C")
print("  4. Verify novelty against 385 known formulas")
print()
print("Estimated: 5-10 new formulas publishable as 1-2 discovery papers.")
print("=" * 78)
