#!/usr/bin/env sage
# verify_universal_obstruction.py
# Given CM modulus results, computes S0, S1 for each family/discriminant
# and checks the universal transcendental obstruction.
# Usage: sage verify_universal_obstruction.py --results cm_results_merged.csv

import argparse, csv, sys, time
from mpmath import mp

mp.mp.dps = 800

# === HYPERGEOMETRIC PARAMETERS (all 16 families, duplicate-free) ===
# Generated by the descent operator S_p with norm() deduplication

FAMILY_PARAMS = {
    # s=1/2 families: |a'|=p, |b'|=p-1, k=1
    "F1": {
        "s": "1/2", "p": 11,
        "a": [mp.mpf(1,1), mp.mpf(1,22), mp.mpf(3,22), mp.mpf(5,22), mp.mpf(7,22), mp.mpf(9,22),
              mp.mpf(13,22), mp.mpf(15,22), mp.mpf(17,22), mp.mpf(19,22), mp.mpf(21,22)],
        "b": [mp.mpf(1,11), mp.mpf(2,11), mp.mpf(3,11), mp.mpf(4,11), mp.mpf(5,11),
              mp.mpf(6,11), mp.mpf(7,11), mp.mpf(8,11), mp.mpf(9,11), mp.mpf(10,11)],
        "k": 1
    },
    "F2": {
        "s": "1/2", "p": 13,
        "a": [mp.mpf(1,2), mp.mpf(1,26), mp.mpf(3,26), mp.mpf(5,26), mp.mpf(7,26), mp.mpf(9,26),
              mp.mpf(11,26), mp.mpf(15,26), mp.mpf(17,26), mp.mpf(19,26), mp.mpf(21,26), mp.mpf(23,26), mp.mpf(25,26)],
        "b": [mp.mpf(1,13), mp.mpf(2,13), mp.mpf(3,13), mp.mpf(4,13), mp.mpf(5,13), mp.mpf(6,13),
              mp.mpf(7,13), mp.mpf(8,13), mp.mpf(9,13), mp.mpf(10,13), mp.mpf(11,13), mp.mpf(12,13)],
        "k": 1
    },
    "F5": {
        "s": "1/3", "p": 11,
        "a": [mp.mpf(1,3), mp.mpf(2,3), mp.mpf(1,33), mp.mpf(2,33), mp.mpf(4,33), mp.mpf(5,33),
              mp.mpf(7,33), mp.mpf(8,33), mp.mpf(10,33), mp.mpf(13,33), mp.mpf(14,33), mp.mpf(16,33),
              mp.mpf(17,33), mp.mpf(19,33), mp.mpf(20,33), mp.mpf(23,33), mp.mpf(25,33), mp.mpf(26,33),
              mp.mpf(28,33), mp.mpf(29,33), mp.mpf(31,33), mp.mpf(32,33)],
        "b": [mp.mpf(1,11), mp.mpf(2,11), mp.mpf(3,11), mp.mpf(4,11), mp.mpf(5,11),
              mp.mpf(6,11), mp.mpf(7,11), mp.mpf(8,11), mp.mpf(9,11), mp.mpf(10,11)],
        "k": 12
    },
    "F9": {
        "s": "1/4", "p": 11,
        "a": [mp.mpf(1,4), mp.mpf(3,4), mp.mpf(1,44), mp.mpf(3,44), mp.mpf(5,44), mp.mpf(7,44),
              mp.mpf(9,44), mp.mpf(13,44), mp.mpf(15,44), mp.mpf(17,44), mp.mpf(19,44), mp.mpf(21,44),
              mp.mpf(23,44), mp.mpf(25,44), mp.mpf(27,44), mp.mpf(29,44), mp.mpf(31,44), mp.mpf(35,44),
              mp.mpf(37,44), mp.mpf(39,44), mp.mpf(41,44), mp.mpf(43,44)],
        "b": [mp.mpf(1,11), mp.mpf(2,11), mp.mpf(3,11), mp.mpf(4,11), mp.mpf(5,11),
              mp.mpf(6,11), mp.mpf(7,11), mp.mpf(8,11), mp.mpf(9,11), mp.mpf(10,11)],
        "k": 12
    },
    "F13": {
        "s": "1/6", "p": 11,
        "a": [mp.mpf(1,6), mp.mpf(5,6), mp.mpf(1,66), mp.mpf(5,66), mp.mpf(7,66), mp.mpf(13,66),
              mp.mpf(17,66), mp.mpf(19,66), mp.mpf(23,66), mp.mpf(25,66), mp.mpf(29,66), mp.mpf(31,66),
              mp.mpf(35,66), mp.mpf(37,66), mp.mpf(41,66), mp.mpf(43,66), mp.mpf(47,66), mp.mpf(49,66),
              mp.mpf(53,66), mp.mpf(59,66), mp.mpf(61,66), mp.mpf(65,66)],
        "b": [mp.mpf(1,11), mp.mpf(2,11), mp.mpf(3,11), mp.mpf(4,11), mp.mpf(5,11),
              mp.mpf(6,11), mp.mpf(7,11), mp.mpf(8,11), mp.mpf(9,11), mp.mpf(10,11)],
        "k": 12
    },
}

def pochhammer_list(vals, n):
    """Compute product of (v)_n for all v in vals using mpmath rgamma."""
    result = mp.mpf(1)
    for v in vals:
        result *= mp.rf(v, n)
    return result

def compute_series(a_list, b_list, k, z0, max_n=20):
    """Compute S0, S1 for the hypergeometric series at modulus z0."""
    s0 = mp.mpf(0)
    s1 = mp.mpf(0)
    for n in range(max_n + 1):
        num = pochhammer_list(a_list, n)
        den = pochhammer_list(b_list, n) * mp.factorial(n)**k
        term = (num / den) * (z0 ** n)
        s0 += term
        s1 += term * n
    return s0, s1

# === MAIN ===
parser = argparse.ArgumentParser()
parser.add_argument("--results", required=True, help="Merged CM results CSV")
parser.add_argument("--families", nargs="*", default=list(FAMILY_PARAMS.keys()),
                    help="Families to verify (default: all)")
parser.add_argument("--pslq", action="store_true", help="Run PSLQ search (slower)")
args = parser.parse_args()

# Read CM results
cm_data = {}
with open(args.results) as f:
    for row in csv.DictReader(f):
        key = (row["Family"], int(row["d"]))
        if row["Status"] == "OK" and row["z0_CM"]:
            cm_data[key] = mp.mpf(row["z0_CM"])

print(f"Loaded {len(cm_data)} CM modulus values")
print(f"Testing families: {args.families}\n")

# Verify each
header = ["Family", "d", "z0_CM", "S0", "S1", "S1/S0", "C~A*pi?", "Prediction"]
rows = []

for fam_id in args.families:
    params = FAMILY_PARAMS[fam_id]
    for d, _, _ in [(1,"",1728), (2,"",8000), (3,"",0), (7,"",-3375), (11,"",-32768),
                      (19,"",-884736), (43,"",-884736000), (67,"",-147197952000), (163,"",-262537412640768000)]:
        key = (fam_id, d)
        if key not in cm_data:
            rows.append([fam_id, d, "MISSING", None, None, None, None, "No CM data"])
            continue
        
        z0_cm = cm_data[key]
        s0, s1 = compute_series(params["a"], params["b"], params["k"], z0_cm)
        
        ratio = float(s1 / s0) if float(s0) > 0 else 0
        obstruction = "YES (S1 << S0 => C~A*pi impossible)" if ratio < 1e-6 else "CHECK"
        
        # Run PSLQ if requested
        prediction = ""
        if args.pslq and obstruction == "CHECK":
            try:
                vec = [float(mp.pi * s0), float(mp.pi * s1), float(-mp.sqrt(s0*s0 + s1*s1))]
                rel = gp.lindep(vec, 20)
                prediction = f"PSLQ: {rel}" if rel else "No integer relation"
            except:
                prediction = "PSLQ failed"
        
        rows.append([fam_id, d, f"{float(z0_cm):.4e}", f"{float(s0):.8f}",
                     f"{float(s1):.4e}", f"{ratio:.4e}", obstruction, prediction])
        
        print(f"[{fam_id}] d={d:3d}: z0={float(z0_cm):.4e}  S0={float(s0):.6f}  S1={float(s1):.4e}  => {obstruction}")

# Save results
outfile = "obstruction_results.csv"
with open(outfile, "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(header)
    w.writerows(rows)

print(f"\nResults saved to {outfile}")

# Summary: count obstruction YES vs CHECK
yes_count = sum(1 for r in rows if r[6] and "YES" in str(r[6]))
check_count = sum(1 for r in rows if r[6] and "CHECK" in str(r[6]))
print(f"Structural obstruction confirmed: {yes_count}/{len(rows)}")
if check_count > 0:
    print(f"Needs further check: {check_count}/{len(rows)}")
